# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b239006bfbf7ff4c8918cc168abe2978377047d99b359d65e0882ae9691e0547a3cc756edbe4cae871c94ce4cc2e3ad105443f85c65645b69bd1e0b430f0d1a

test:
  secret_key_base: fcf8ce070a618af163930407a312f868190744d38feeb16835e5a7cc9219d7fc91f8ac876c14d468886f04165d48666f0ea0d869b2bc4fac8ad5a065f7dcf6ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
